image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: true
    addBadge: false
    addLabel: false
tasks:
- command: |
    export PATH=/usr/lib/dart/bin:$FLUTTER_HOME/bin:$ANDROID_CMDLINE_TOOLS/tools/bin:$PATH
vscode:
  extensions:
    - Dart-Code.flutter@3.15.0:yOpvKlbjJs29tD2wFEr6sw==
    - Dart-Code.dart-code@3.15.0:hFWw2I7MsnbvCrn1WIB8bA==